package models

import (
	"time"
)

// VideoStatus represents the lifecycle state of a video.
type VideoStatus string

const (
	StatusDraft      VideoStatus = "draft"
	StatusUploading  VideoStatus = "uploading"
	StatusProcessing VideoStatus = "processing"
	StatusReady      VideoStatus = "ready"
	StatusFailed     VideoStatus = "failed"
	StatusScheduled  VideoStatus = "scheduled"
	StatusDeleted    VideoStatus = "deleted"
)

// VideoVisibility controls who can see a published video.
type VideoVisibility string

const (
	VisibilityPublic   VideoVisibility = "public"
	VisibilityPrivate  VideoVisibility = "private"
	VisibilityFriends  VideoVisibility = "friends"
)

// Video is the central domain entity.
type Video struct {
	ID          string          `json:"id"           db:"id"`
	UserID      string          `json:"user_id"      db:"user_id"`
	Title       string          `json:"title"        db:"title"`
	Description string          `json:"description"  db:"description"`
	Status      VideoStatus     `json:"status"       db:"status"`
	Visibility  VideoVisibility `json:"visibility"   db:"visibility"`

	// Raw upload location (S3 key of the original file).
	RawKey string `json:"raw_key" db:"raw_key"`

	// HLS master playlist S3 key (set after transcoding).
	HLSKey string `json:"hls_key" db:"hls_key"`

	// Public CDN URL of the HLS master playlist.
	HLSUrl string `json:"hls_url" db:"hls_url"`

	// Counts (maintained by counters service / triggers).
	LikeCount    int64 `json:"like_count"    db:"like_count"`
	CommentCount int64 `json:"comment_count" db:"comment_count"`
	ShareCount   int64 `json:"share_count"   db:"share_count"`
	ViewCount    int64 `json:"view_count"    db:"view_count"`

	// Hashtags stored as a simple text array.
	Tags []string `json:"tags" db:"tags"`

	// Sound / music track ID (optional).
	SoundID string `json:"sound_id,omitempty" db:"sound_id"`

	// Scheduling.
	PublishAt *time.Time `json:"publish_at,omitempty" db:"publish_at"`

	// Timestamps.
	CreatedAt time.Time  `json:"created_at" db:"created_at"`
	UpdatedAt time.Time  `json:"updated_at" db:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at,omitempty" db:"deleted_at"`
}

// VideoChunk represents one piece of a chunked upload in progress.
type VideoChunk struct {
	ID       string `json:"id"        db:"id"`
	UploadID string `json:"upload_id" db:"upload_id"`
	VideoID  string `json:"video_id"  db:"video_id"`
	Index    int    `json:"index"     db:"chunk_index"`

	// S3 key of the stored chunk object.
	S3Key string `json:"s3_key" db:"s3_key"`

	// Size in bytes.
	Size int64 `json:"size" db:"size"`

	// SHA-256 checksum for integrity verification.
	Checksum string `json:"checksum" db:"checksum"`

	CreatedAt time.Time `json:"created_at" db:"created_at"`
}

// Thumbnail is a still image extracted from the video.
type Thumbnail struct {
	ID       string `json:"id"        db:"id"`
	VideoID  string `json:"video_id"  db:"video_id"`
	S3Key    string `json:"s3_key"    db:"s3_key"`
	URL      string `json:"url"       db:"url"`
	Width    int    `json:"width"     db:"width"`
	Height   int    `json:"height"    db:"height"`
	// OffsetSecs is the position in the source video where this frame was grabbed.
	OffsetSecs float64   `json:"offset_secs" db:"offset_secs"`
	IsCover    bool      `json:"is_cover"    db:"is_cover"`
	CreatedAt  time.Time `json:"created_at"  db:"created_at"`
}

// SubtitleFormat enumerates supported subtitle container formats.
type SubtitleFormat string

const (
	SubtitleSRT  SubtitleFormat = "srt"
	SubtitleVTT  SubtitleFormat = "vtt"
	SubtitleJSON SubtitleFormat = "json" // Whisper JSON transcript
)

// Subtitle is a generated or uploaded caption track.
type Subtitle struct {
	ID       string         `json:"id"        db:"id"`
	VideoID  string         `json:"video_id"  db:"video_id"`
	Language string         `json:"language"  db:"language"` // ISO-639-1
	Format   SubtitleFormat `json:"format"    db:"format"`
	S3Key    string         `json:"s3_key"    db:"s3_key"`
	URL      string         `json:"url"       db:"url"`
	// AutoGenerated is true when produced by the Whisper pipeline.
	AutoGenerated bool      `json:"auto_generated" db:"auto_generated"`
	CreatedAt     time.Time `json:"created_at"     db:"created_at"`
}

// VideoQuality holds the S3 location and stream details for one transcoded rendition.
type VideoQuality struct {
	Name         string `json:"name"`          // e.g. "720p"
	Width        int    `json:"width"`
	Height       int    `json:"height"`
	VideoBitrate string `json:"video_bitrate"` // e.g. "2500k"
	AudioBitrate string `json:"audio_bitrate"` // e.g. "128k"
	S3Key        string `json:"s3_key"`        // HLS sub-playlist S3 key
	URL          string `json:"url"`
}

// VideoMetadata stores technical properties extracted from the source video.
type VideoMetadata struct {
	ID       string `json:"id"        db:"id"`
	VideoID  string `json:"video_id"  db:"video_id"`

	// Duration in seconds.
	DurationSecs float64 `json:"duration_secs" db:"duration_secs"`

	// Source dimensions.
	Width  int `json:"width"  db:"width"`
	Height int `json:"height" db:"height"`

	// Codec identifiers.
	VideoCodec string `json:"video_codec" db:"video_codec"` // e.g. "h264"
	AudioCodec string `json:"audio_codec" db:"audio_codec"` // e.g. "aac"

	// Frame rate as a rational approximation.
	FrameRate float64 `json:"frame_rate" db:"frame_rate"` // e.g. 29.97

	// Raw file size in bytes.
	FileSizeBytes int64 `json:"file_size_bytes" db:"file_size_bytes"`

	// MIME type of the original upload.
	MIMEType string `json:"mime_type" db:"mime_type"`

	// Available transcoded qualities (stored as JSONB in Postgres).
	Qualities []VideoQuality `json:"qualities" db:"qualities"`

	// Aspect ratio string e.g. "9:16".
	AspectRatio string `json:"aspect_ratio" db:"aspect_ratio"`

	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
}

// UploadSession tracks the state of an in-progress chunked upload.
// It is stored in Redis (JSON-serialised) keyed by upload_id.
type UploadSession struct {
	UploadID      string    `json:"upload_id"`
	VideoID       string    `json:"video_id"`
	UserID        string    `json:"user_id"`
	Filename      string    `json:"filename"`
	MIMEType      string    `json:"mime_type"`
	TotalSize     int64     `json:"total_size"`
	TotalChunks   int       `json:"total_chunks"`
	ChunkSize     int64     `json:"chunk_size"`
	ReceivedChunks []int    `json:"received_chunks"` // sorted list of received chunk indices
	CreatedAt     time.Time `json:"created_at"`
	ExpiresAt     time.Time `json:"expires_at"`
}

// UploadProgress is returned by the progress endpoint.
type UploadProgress struct {
	UploadID       string  `json:"upload_id"`
	VideoID        string  `json:"video_id"`
	TotalChunks    int     `json:"total_chunks"`
	ReceivedChunks int     `json:"received_chunks"`
	PercentDone    float64 `json:"percent_done"`
	MissingChunks  []int   `json:"missing_chunks"`
	Status         string  `json:"status"`
}

// VideoUploadedEvent is the Kafka event produced when a raw upload is complete.
type VideoUploadedEvent struct {
	VideoID   string    `json:"video_id"`
	UserID    string    `json:"user_id"`
	RawS3Key  string    `json:"raw_s3_key"`
	MIMEType  string    `json:"mime_type"`
	FileSize  int64     `json:"file_size"`
	CreatedAt time.Time `json:"created_at"`
}

// VideoTranscodedEvent is the Kafka event produced when transcoding completes.
type VideoTranscodedEvent struct {
	VideoID    string         `json:"video_id"`
	HLSKey     string         `json:"hls_key"`
	HLSUrl     string         `json:"hls_url"`
	Qualities  []VideoQuality `json:"qualities"`
	Thumbnails []Thumbnail    `json:"thumbnails"`
	Metadata   VideoMetadata  `json:"metadata"`
	CompletedAt time.Time     `json:"completed_at"`
}

// CreateVideoRequest is the payload for creating a new video record.
type CreateVideoRequest struct {
	UserID      string          `json:"user_id"      binding:"required"`
	Title       string          `json:"title"        binding:"required,max=150"`
	Description string          `json:"description"  binding:"max=2200"`
	Visibility  VideoVisibility `json:"visibility"   binding:"required,oneof=public private friends"`
	Tags        []string        `json:"tags"`
	SoundID     string          `json:"sound_id"`
	PublishAt   *time.Time      `json:"publish_at"`
}

// UpdateVideoRequest is the payload for updating video metadata.
type UpdateVideoRequest struct {
	Title       *string          `json:"title"       binding:"omitempty,max=150"`
	Description *string          `json:"description" binding:"omitempty,max=2200"`
	Visibility  *VideoVisibility `json:"visibility"  binding:"omitempty,oneof=public private friends"`
	Tags        []string         `json:"tags"`
	SoundID     *string          `json:"sound_id"`
	PublishAt   *time.Time       `json:"publish_at"`
}

// InitiateUploadRequest starts a new chunked upload session.
type InitiateUploadRequest struct {
	Filename    string `json:"filename"    binding:"required"`
	MIMEType    string `json:"mime_type"   binding:"required"`
	TotalSize   int64  `json:"total_size"  binding:"required,gt=0"`
	TotalChunks int    `json:"total_chunks" binding:"required,gt=0"`
	ChunkSize   int64  `json:"chunk_size"  binding:"required,gt=0"`
}

// InitiateUploadResponse is returned to the client after upload initiation.
type InitiateUploadResponse struct {
	UploadID    string `json:"upload_id"`
	VideoID     string `json:"video_id"`
	TotalChunks int    `json:"total_chunks"`
	ChunkSize   int64  `json:"chunk_size"`
}
